import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
  discordLogin: (authUrl: string) => ipcRenderer.invoke('discord-login', authUrl),
  enterMiniPlayer: () => ipcRenderer.send('enter-mini-player'),
  exitMiniPlayer: () => ipcRenderer.send('exit-mini-player'),
  closeMiniPlayerWindow: () => ipcRenderer.send('close-mini-player-window'),
  onMiniPlayerClosed: (callback: () => void) => ipcRenderer.on('mini-player-closed', callback),
  isMiniPlayerWindow: () => new URLSearchParams(window.location.search).get('miniplayer') === 'true',
  getPlaylists: (discordId?: string) => ipcRenderer.invoke('get-playlists', discordId),
  savePlaylist: (playlist: any) => ipcRenderer.invoke('save-playlist', playlist),
  deletePlaylist: (id: string) => ipcRenderer.invoke('delete-playlist', id),
  onUpdateAvailable: (callback: (event: any, info: any) => void) => ipcRenderer.on('update-available', callback),
  onUpdateDownloaded: (callback: (event: any, info: any) => void) => ipcRenderer.on('update-downloaded', callback),
  onDownloadProgress: (callback: (event: any, progressObj: any) => void) => ipcRenderer.on('download-progress', callback),
  onUpdateError: (callback: (event: any, error: string) => void) => ipcRenderer.on('update-error', callback),
  downloadUpdate: () => ipcRenderer.send('download-update'),
  installUpdate: () => ipcRenderer.send('install-update'),
  updatePresence: (data: any) => ipcRenderer.invoke('update-presence', data),
  getOnlineUsers: (currentUserId: string) => ipcRenderer.invoke('get-online-users', currentUserId),
  hostParty: (partyId: string, hostDiscordId: string, song: any, currentTime: number, isPlaying: boolean) => ipcRenderer.invoke('host-party', partyId, hostDiscordId, song, currentTime, isPlaying),
  getPartyState: (partyId: string) => ipcRenderer.invoke('get-party-state', partyId),
  deleteParty: (partyId: string) => ipcRenderer.invoke('delete-party', partyId),
  sendJoinRequest: (hostId: string, guestId: string, guestName: string) => ipcRenderer.invoke('send-join-request', hostId, guestId, guestName),
  pollJoinRequests: (userId: string) => ipcRenderer.invoke('poll-join-requests', userId),
  respondJoinRequest: (requestId: number, status: string) => ipcRenderer.invoke('respond-join-request', requestId, status),
  sendQueueRequest: (hostId: string, guestId: string, guestName: string, songData: any) => ipcRenderer.invoke('send-queue-request', hostId, guestId, guestName, songData),
  pollQueueRequests: (hostId: string) => ipcRenderer.invoke('poll-queue-requests', hostId),
  respondQueueRequest: (requestId: number, status: string) => ipcRenderer.invoke('respond-queue-request', requestId, status),
  romanizeLyrics: (text: string, lang: 'ko' | 'ja') => ipcRenderer.invoke('romanize-lyrics', text, lang),
  setActivity: (song: any, progressStr?: string) => ipcRenderer.send('set-activity', song, progressStr),
  clearActivity: () => ipcRenderer.send('clear-activity'),
  onDiscordOAuthToken: (callback: (token: string) => void) =>
    ipcRenderer.on('discord-oauth-token', (_event, token) => callback(token)),
  checkCache: (songId: string) => ipcRenderer.invoke('check-cache', songId),
  cacheAudio: (songId: string, url: string) => ipcRenderer.send('cache-audio', songId, url),
  clearCache: () => ipcRenderer.invoke('clear-cache'),
  getCacheSize: () => ipcRenderer.invoke('get-cache-size'),
});
